
import { useRef, useEffect } from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import function to register Swiper custom elements
import { register } from 'swiper/element/bundle';
import { Toaster } from '@/components/ui/toaster';
// register Swiper custom elements
register();

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-element-bundle.min.js"></script>
      </head>
      <body className={inter.className}>{children}
      <Toaster />
      </body>
      
    
    </html>
  );
}



